services:
  - type: web
    name: portfolio-jibhar
    env: node
    buildCommand: npm run build && npm run db:push -- --force
    startCommand: npm run start
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
